import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart' as fs;
import 'package:flutter/foundation.dart'
    show LicenseEntryWithLineBreaks, LicenseRegistry;

import 'imports.dart';
import 'routes.dart';
import 'services/auth_service.dart';
import 'screens/dashboard/dashboard_screen.dart';
import 'firebase_options.dart'; // ← Ensure this exists (generated by FlutterFire CLI)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Register Google Fonts license
  LicenseRegistry.addLicense(() async* {
    final license = await rootBundle.loadString(
      'assets/fonts/Amatic_SC/OFL.txt',
    );
    yield LicenseEntryWithLineBreaks(['google_fonts'], license);
  });

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Enable Firestore offline persistence
  fs.FirebaseFirestore.instance.settings = const fs.Settings(
    persistenceEnabled: true,
    cacheSizeBytes: fs.Settings.CACHE_SIZE_UNLIMITED,
  );

  // Run app with provider
  runApp(
    MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => ProjectsProvider())],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Close2Source',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.white,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
      ),
      routes: {
        AppRoutes.login: (context) => const LoginScreen(),
        AppRoutes.register: (context) => const UserRegistrationForm(),
        AppRoutes.dashboard: (context) => const DashboardScreen(),
      },
      home: const AuthGate(),
    );
  }
}

class AuthGate extends StatefulWidget {
  const AuthGate({super.key});

  @override
  State<AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<AuthGate> {
  @override
  void initState() {
    super.initState();
    AuthService().handleAuthState(context);
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold(body: Center(child: CircularProgressIndicator()));
  }
}
